### ISSUE TITLE
Allow null to be captured by input type

### ISSUE THREAD

**Issue by alaarihan** [async-graphql/async-graphql#1201]
## Expected Behavior
handle null as Some(String) or something when the graphql query contains the field with null as a value.
So this query can be handled to set description to null
```
#[derive(Clone, Debug, PartialEq, InputObject)]
pub struct PostInput {
    pub title: Option<String>,
    pub description: Option<String>,
}
```

```
mutation{
  updatePost(data:{title: "Post 1"  description: null}, id: 38){
    id
    description
  }
}
```

## Actual Behavior
The optional field will be None if it's not exist in the graphql query and it will also be None if it was exist in the query but has null as a value

Right now this query >>>
```
mutation{
  updatePost(data:{title: "Post 1"  description: null}, id: 38){
    id
    description
  }
}
```

Is similar to this one
```
mutation{
  updatePost(data:{title: "Post 1" }, id: 38){
    id
    description
  }
}
```

In current situation we can't update description field to be null!

**Comment by xamgore** [comment]
According to the [spec](https://spec.graphql.org/October2021/#sec-Null-Value), absent values and the `null` value have different semantic meanings. What you really need is `MaybeUndefined<String>` type. It is similar to `Option`, but it has three states: `undefined`, `null`, and `T`.

```rust
use async_graphql::*;

struct Query;

#[Object]
impl Query {
    async fn value1(&self, input: MaybeUndefined<i32>) -> i32 {
        if input.is_null() {
            1
        } else if input.is_undefined() {
            2
        } else {
            input.take().unwrap()
        }
    }
}
```

I believe the issue can be closed now.

**Comment by alaarihan** [comment]
Thank you very much, I searched for a solution for days but I did not find this, could you please mention it in the documentation?

**Comment by EXPEylazzari** [comment]
Plus one to what @alaarihan said above. I also just stumbled on this answer. It didn't take me too long to find it by simply searching for "null" in the history of issues to see if someone had raised the question in the past, but searching the [book](https://async-graphql.github.io/async-graphql/en/introduction.html) for "MaybeUndefined" yields no result. The only other place to find it otherwise is if you actually go through and browse all the crate's documentation, which again not that hard, but not the most discoverable. Please consider adding a small section in the book to cover this topic, or maybe an entire section devoted to all the types of the `async_graphql::types` module. Just a suggestion. Thank you!

**Comment by frederikhors** [comment]
@EXPEylazzari can you please PR?
