### ISSUE TITLE
Why are non-root mutations not supported?

### ISSUE THREAD

**Issue by tdejager** [async-graphql/async-graphql#1283]
I think I can gather from this issue: https://github.com/async-graphql/async-graphql/issues/521 that you are not in favor of having mutations that are not directly in the root object. I don't know if my reading of this is correct?

If so, could you maybe clarify why you think this is an incorrect usage of GraphQL? As I see it it is allowed in the specification, and in some cases even recommended?

**Comment by nikis05** [comment]
It is not allowed in specification because queries are allowed to execute in parallel with each other while mutations are not. So there would be no predictable and non-confusing way to execute something like this:

```graphql
query {
    user(id: 123) {
        friends {
            id     # I get list of a user's friends
        }
        removeFromFriendList # In the same operation, I remove myself from that list. So should I be on the list then that gets returned?
    }
}
```

The spec could hypothetically come up with some set of obscure rules that would specify how such query should be run, but it would be confusing and bug prone for API users.

On the other hand:

```graphql
mutation {
    unfriendUser(id: 123) {
        friends {
            id
        }
    }
}
```

In this case it is clear that we are querying fields of a mutated object after a mutation.

Kind of remotely reminiscent of Rust's borrowing rules, you can have as many simultaneous "immutable borrows" as you like but only one "mutable borrow" 😅

**Comment by tdejager** [comment]
Thanks that makes sense! And is there no way of namespacing the mutations in some way?

**Comment by nikis05** [comment]
@tdejager unfortunately there is no first-class language supported way, but no one prevents you from giving prefixes to your mutation names, such as `userCreate`, `noteCreate` and so on.

But I wouldn't worry too much about it tbh, I work at a pretty big project with nearly 100 distinct mutations, and navigating mutations hasn't become a problem yet.

**Comment by tdejager** [comment]
Thank you, sounds good :) I'll close this question then.
