### ISSUE TITLE
How to get ordered argument fields?

### ISSUE THREAD

**Issue by iynaix** [async-graphql/async-graphql#1390]
Given the following schema and graphql queries with their order fields swapped:

```rust
#[derive(SimpleObject, Debug)]
pub struct Person {
    age: i32,
    name: String,
}

#[derive(InputObject, Debug)]
pub struct PersonOrder {
    age: Option<i32>,
    name: Option<String>,
}

pub struct QueryRoot;

#[Object]
impl QueryRoot {
    async fn person<'a>(&self, _ctx: &Context<'a>, order: Option<PersonOrder>) -> Person {
        if let Some(order) = order {
            if let Value::Object(value) = order.to_value() {
                value.iter().for_each(|(k, v)| {
                    println!("{}: {:?}", k, v);
                });
            }
        };

        Person {
            name: "Jane".to_string(),
            age: 20,
        }
    }
}
```
```gql
{
  person(order: {  name: "John", age: 41}) {
    name
  }
}
```

```gql
{
  person(order: {  age: 41, name: "John"}) {
    name
  }
}
```
Both of the queries produce the same debug output with  the fields in the same alphabetical order. Ideally it should reflect the same order as the query as the key order matters for sorting.
```
age: Number(Number(20))
name: String("Jane")
```

I'm not sure if this is a bug or is there another way to do this?

**Comment by xamgore** [comment]
The order is defined by schema types i.e. `PersonOrder` is an input type with two fields: the first one is `age`, and the second is `name`. The parsing goes in the same way: pick `age` then `name`. As you call `to_value()`, we have an influence of IndexMap, which preserves the requested(!) fields order. Macro expansion:

```rust
 fn parse(value: ::std::option::Option<async_graphql::Value>) -> async_graphql::InputValueResult<Self> {
    if let ::std::option::Option::Some(async_graphql::Value::Object(obj)) = value {
      #[allow(non_snake_case, unused_mut)]
      let mut age: Option<i32> = 
        async_graphql::InputType::parse(obj.get("age").cloned()).map_err(async_graphql::InputValueError::propagate)?;
      #[allow(non_snake_case, unused_mut)]
      let mut name: String = 
        async_graphql::InputType::parse(obj.get("name").cloned()).map_err(async_graphql::InputValueError::propagate)?;
      let obj = Self { age, name };
      ::std::result::Result::Ok(obj)
    } else { ::std::result::Result::Err(async_graphql::InputValueError::expected_type(value.unwrap_or_default())) }
  }

  fn to_value(&self) -> async_graphql::Value {
    let mut map = async_graphql::indexmap::IndexMap::new();
    map.insert(async_graphql::Name::new("age"), async_graphql::InputType::to_value(&self.age));
    map.insert(async_graphql::Name::new("name"), async_graphql::InputType::to_value(&self.name));
    async_graphql::Value::Object(map)
  }
```

That's why it happens.

I may suggest trying a list of [`OneofObject`](https://async-graphql.github.io/async-graphql/en/define_one_of_object.html): `[{ age: ... }, { name: ... }]`. The second option is [defining a scalar](https://async-graphql.github.io/async-graphql/en/custom_scalars.html) and manually deserializing it into BTreeMap/[IndexMap](https://docs.rs/async-graphql/latest/async_graphql/enum.Value.html#variants). The third option is a manual `#[InputObject]` implementation.

**Comment by iynaix** [comment]
Thanks for the explanation, I've decided to go for the OneofObject approach. :+1:
