### ISSUE TITLE
Support Upload Stream

### ISSUE THREAD

**Issue by nicolaiunrein** [async-graphql/async-graphql#15]
The `Upload` type should provide a stream of bytes instead of a `Vec<u8>` leaving it to the user to decide what to do with it eg. stream it into a tempfile. I think loading the file contents into memory is a big performance and security issue.

Alternatively let the user define a location for uploads (eg. /tmp) and stream the content into files at this location and pass handles to these files to the user. 

The second solution might be easier to integrate into the existing codebase although as a library user I would much prefer the first solution, giving me more control (eg. the opportunity to cancel requests early on  before loading the contents / if not enough disk space is available / dynamic filesize checks / streaming to 3rd party APIs etc.)

**Comment by sunli829** [comment]
I'm also leaning towards the first option, and I want to remove the dependency on the `actix-multipart` to make it more compatible with other web servers. I searched existing crates and didn't have a working asynchronous multipart parser, so I probably had to write a new one.

Then add a function like `Schema::query_from_request<R: AsyncRead>(&self, content_type: &str, body: R)`, should be easier to use.

**Comment by nicolaiunrein** [comment]
Sounds good. :thumbsup:

**Comment by sunli829** [comment]
I ended up choosing the first option because the second option had some problems with the order of requests.

**Comment by sunli829** [comment]
Actually, I am preparing to implement `Read` for `Upload`, which will probably be completed tomorrow. 😁

**Comment by nicolaiunrein** [comment]
Sorry didn’t realise. That’ll awesome!

**Comment by Sytten** [comment]
@sunli829 I was reading the code and as far as I understand the file needs to be completely uploaded (either in memory or in temp) before it is returned as an async stream. This is not great for large files where you might want to stream the data without buffering it. Unsure if it is doable though.

**Comment by sunli829** [comment]
This is very difficult to achieve, and I don't think GraphlQL can do it. 🙂

**Comment by Sytten** [comment]
So I was reading about it, I think it would be possible but only when you have one file. In theory we could get a stream of the body directly from the TCP stream after we read the query and the map of files.

But if you upload more than one file you need to buffer for sure to the disk. Still for a lot of cases it would be a worthwhile optimisation. Just unsure if you want to support it @sunli829 

My use case is that users are uploading large files to the server and since tempfile is used I can't just move them where I want, I have to copy them so for a bit of time I have 2x the disk usage which is annoying. An alternative that would work for me would be to have a named file, so maybe that would be a better approach (just another feature flag).

**Comment by nicolaiunrein** [comment]
I‘m reading this thread since I originally opened the issue. I currently do not use this library anymore. Just wondering @Sytten can‘t you just [persist](https://docs.rs/tempfile/latest/tempfile/struct.TempPath.html#method.persist) the tempfile? In general I think it would be good if one could get a raw reference to an AsyncRead of the uploaded content.

**Comment by sunli829** [comment]
> So I was reading about it, I think it would be possible but only when you have one file. In theory we could get a stream of the body directly from the TCP stream after we read the query and the map of files.

You are right, it can indeed be optimized when only one file is uploaded, I will think about it. 🙂
