### ISSUE TITLE
Exporting schema with code first definition

### ISSUE THREAD

**Issue by olibearo** [async-graphql/async-graphql#191]
What is the recommended flow for this? It would be preferable to export it programmatically.
 
I want to use my schema with [graphql-client](https://github.com/graphql-rust/graphql-client) and it asks for a schema file. If there is a better Rust client, maybe one which can introspect the schema, I would appreciate the recommendation.

**Comment by phated** [comment]
You can use a bunch of tools to fetch the schema from your server. I use https://www.npmjs.com/package/graphql-cli/v/3.0.14 (version 3 because the new authors completely changed the project) to fetch and save my schema into the project.

This also came up at https://github.com/async-graphql/async-graphql/issues/68#issuecomment-643305339 and we decided using a tool to fetch the schema is the best approach.

Side note: it is a recommended practice to commit your schema and have a CI process that verifies the introspection query and committed schema match.

**Comment by olibearo** [comment]
Appreciate the tip @phated

**Comment by Weasy666** [comment]
So...i would like to mention, that a lot of GraphQL libraries offer a functionality to export/print a schema. For example, GraphQL-Ruby has the `Schema::Printer` class and GraphQL-JS has the `printSchema` method which take a schema object/class and export/print it as an artifact, which then can be used for validation.

I don't think an external tool that first needs a running GraphQL web server to fetch the schema is ideal. With the print function built in to `async-graphql` you could easily validate your schema at build time instead of at runtime.

**Comment by Koxiaet** [comment]
@Weasy666 In your example how is `async-graphql` supposed to know about `Node`? We can't use global state because then any crate could just add arbitrary types to your schema. You can [manually register types in your schema](https://docs.rs/async-graphql/1.18.1/async_graphql/struct.SchemaBuilder.html#method.register_type) if you wish.

**Comment by Weasy666** [comment]
That was not the initial point i wanted to make, but...doesn't `async-graphql` already know about `Node`? I thought `#[derive(GQLInterface)]` specifies that the `Node` enum is an interface for every struct that is the inner value of one of the enum variants.

But...that i think that this issue is not the right place for that topic. If the point of validating a schema on build time instead of on runtime is not convincing on its own, then another scenario i can think of, is the immediate overview a developer can have over the generated API after implementing some new types or after doing some modifications. He can print the schema after/while building his application and directly compare/diff it to the previous version.

**Comment by sunli829** [comment]
I adding export `SDL` now...

**Comment by Koxiaet** [comment]
What about implementing `Display` for `Schema` instead and doing everything through `Formatter` instead of `String`?

**Comment by sunli829** [comment]
> What about implementing `Display` for `Schema` instead and doing everything through `Formatter` instead of `String`?

The advantage of implementing `Display` is that it can reduce memory allocation, for example, directly output to `stdout`, but because this function is not called frequently, so if there is a need to optimize later. 😁
