### ISSUE TITLE
Introspection query fails when query depth/complexity limit is specified

### ISSUE THREAD

**Issue by rkudryashov** [async-graphql/async-graphql#209]
If I specify

```
    Schema::build(Query, Mutation, Subscription)
        .limit_complexity(15)
        .limit_depth(3)
```

then docs stop showing in, for example, embedded Playground. But by specifying limits I want to restrict only _real_ expensive queries. Is there a way to determine whether some query is an introspection query not to apply those limits to it?

**Comment by sunli829** [comment]
I think the best way is to turn off introspection queries in a production environment.

**Comment by rkudryashov** [comment]
I think the issue can be closed if no one can add something to the discussion :)

**Comment by onx2** [comment]
> I think the best way is to turn off introspection queries in a production environment.

How would one do this? The only information in the book I can see regarding introspection is how to [hide content](https://async-graphql.github.io/async-graphql/en/visibility.html?highlight=introspect#hide-content-in-introspection).

**Comment by sunli829** [comment]
> > I think the best way is to turn off introspection queries in a production environment.
> 
> 
> 
> How would one do this? The only information in the book I can see regarding introspection is how to [hide content](https://async-graphql.github.io/async-graphql/en/visibility.html?highlight=introspect#hide-content-in-introspection).

Call the `SchemaBuilder::disable_introspection` at building the Schema.

**Comment by sillen102** [comment]
> I think the best way is to turn off introspection queries in a production environment.

I'm running into the issue described here as well and I would strongly disagree. If you are building an API that can be consumed by a third party (customer or client) you would want to offer a playground in a sandbox/testing environment for them to test and play around with to build their queries.

Then they build an integration to your API using this information and eventually go to production where all of their queries fail because the settings for complexity, depth etc. was turned off in your sandbox environment but is turned on in production.

**Comment by sillen102** [comment]
> SchemaBuilder::disable_introspection

But you would want to have the same settings in your production environment and your testing environment? I agree you would want to turn off the introspection queries in production, however you would want to have them in your testing environment. And you would also want to have the same settings for limiting query complexity in testing as you would in production.

So if you do have settings for limiting complexity in your testing environment then the introspections won't work and you can't have a playground. And if you want to have a playground, for let's say third party integrators to your API, then you would want to have the same settings for limitations as in production.

Because if you have different settings in testing vs. production your integrators will spend lots of time and money building an integration to your API and then have queries fail in production because suddenly there are limitations in place that you were forced to turn off in your testing environment.
