### ISSUE TITLE
Persisted queries.

### ISSUE THREAD

**Issue by meh** [async-graphql/async-graphql#280]
Is it me or are [persisted queries](https://www.apollographql.com/docs/react/api/link/persisted-queries/) impossible to implement with the current `Extension` trait?

**Comment by Koxiaet** [comment]
Yeah, they would actually require some changes to implement. We have an `extensions` field on `Request` but it contains `async-graphql` extensions not GraphQL extensions - we'll have to change that. Additionally it means that the `query` field of a request has to be `Option<String>` instead of `String` (or maybe we can simply add `#[serde(default)]` to it).

**Comment by meh** [comment]
I'd really like for this to be possible to implement before #208 happens, I was going to abuse the extension to also do demand control :(

**Comment by sunli829** [comment]
I am adding this feature.

**Comment by meh** [comment]
Thank you so much, you're a hero!

**Comment by sunli829** [comment]
Only support memory-based LRU cache right now. If you need to support `Redis`,  need to implement `CacheStorage` yourself, which is very easy.

**Comment by sunli829** [comment]
If the problem has been resolved, please close it.
