### ISSUE TITLE
Decimal precision

### ISSUE THREAD

**Issue by benjamingb** [async-graphql/async-graphql#325]
I have the following structure

```
#[derive(SimpleObject)]
pub struct ProductType {
    pub sku: String,
    pub description: String,
    pub area: String,
    pub quantity: i32,
    pub price: f32,
    pub total: f32,
}
```

In the price field I am putting _5.66_, but I get _5.659999847412109_
**price: 5.66** => **price: 5.659999847412109**

How can I get only 2 decimal places?
```
{
  "data": {
    "products": [
      {
        "price": 5.659999847412109,
        "quantity": 1,
        "sku": "2324",
        "total": 5.659999847412109,
      }
    ]
  }
}
```

**Comment by Koxiaet** [comment]
The issue that 5.659999847412109 is technically the correct value; f32 can't represent 5.66 fully, and that value is a more faithful representation to what the f32 is than "5.66" is. We use this more accurate represention because we use `serde_json` internally and [it uses an f64 to store numbers](https://docs.rs/serde_json/1.0.59/serde_json/struct.Number.html#method.from_f64). You can round it before you crate the object, or you can define a custom scalar that rounds it before creating the `serde_json::Number`.

**Comment by benjamingb** [comment]
Thanks 

use f64 and it solved the problem

```
#[derive(SimpleObject)]
pub struct ProductType {
    pub sku: String,
    pub description: String,
    pub area: String,
    pub quantity: i32,
    pub price: f64,
    pub total: f64,

 ```
