### ISSUE TITLE
subscription support in tide

### ISSUE THREAD

**Issue by TsumiNa** [async-graphql/async-graphql#360]
Do you have any plan to support subscriptions in the tide? They already had their [WebSocket](https://docs.rs/tide-websockets/0.1.0/tide_websockets/) crate and planing to merge it into tide itself.

**Comment by sunli829** [comment]
I'm sorry to reply you late because of something.
In fact, I have added support for tide-websockets in the branch of `tide-websocket`, so I opened a [PR](https://github.com/http-rs/tide-websockets/pull/1 ), now you need to wait for a new version of `tide-websockets` to be released.

In addition, I personally do not recommend using `tide`, because it lacks a lot of functions, `actix-web` or `warp` (if you can master it 🙂) should be a better choice.

**Comment by TsumiNa** [comment]
Thanks for your suggestion! I'm learning rust sync and found that tide is a good starting point for me. I also have tried warp a little. The chained router system is so unique.

**Comment by extraymond** [comment]
@sunli829  Hi! tide-websocket has received a new release that includes the PR, are there any blockers for subscription over websocket to happen for async-graphql-tide?  Thanks for your effort, really enjoying the crates.

**Comment by sunli829** [comment]
Release in `v2.5.2`   🙂

**Comment by extraymond** [comment]
@sunli829 You are the best!!!
