### ISSUE TITLE
Data loader and look ahead

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#412]
Hi,

I am looking at data loader example: https://github.com/async-graphql/examples/blob/master/tide/dataloader/src/main.rs

I have some questions:

1. I am not sure if data-loader will batch all requests to database? even with `load_one`

2. On this particular line, I am not sure how to get look ahead ids out and apply to the SQL query https://github.com/async-graphql/examples/blob/master/tide/dataloader/src/main.rs#L42

Thanks for this well rounded library!

**Comment by phungtranminh** [comment]
I quickly read through https://github.com/async-graphql/async-graphql/blob/master/src/dataloader/mod.rs#L172

Looks like there is a delay (like 1ms) to wait before the library making some requests, perhaps probably to do batch loading?

Having a configurable number is a bit tricky as I am not sure what is the best number?

**Comment by Bajix** [comment]
I originally addressed this issue by use of preloads, which could be as simple as using a lookahead to do batch load and having field resolvers that check for preloaded data. That pattern works well and has the fastest response times by virtue of there being no locks and no delays, but it misses the opportunity to batch load across independent requests which is preferable at scale. I thought it to be cleaner to use the dataloader and built out some new behavior using it, but then we experienced deadlocks on this field and had to disable this behavior which is why I came to post before I saw this. When I was experiencing deadlocks this was with a 1ms delay, and I'm not sure if increasing the delay will decrease the likelihood of a deadlock. 

@sunli829 it occurs to me that there are several ways in which crossbeam could be used as to make this lock free, either via crossbeam deque or crossbeam channels. Still brainstorming on that though

**Comment by sunli829** [comment]
> I quickly read through https://github.com/async-graphql/async-graphql/blob/master/src/dataloader/mod.rs#L172
> 
> Looks like there is a delay (like 1ms) to wait before the library making some requests, perhaps probably to do batch loading?
> 
> Having a configurable number is a bit tricky as I am not sure what is the best number?

Yes, `DataLoader` will merge all queries during this period, 1-10ms I think is good.

**Comment by sunli829** [comment]
> I originally addressed this issue by use of preloads, which could be as simple as using a lookahead to do batch load and having field resolvers that check for preloaded data. That pattern works well and has the fastest response times by virtue of there being no locks and no delays, but it misses the opportunity to batch load across independent requests which is preferable at scale. I thought it to be cleaner to use the dataloader and built out some new behavior using it, but then we experienced deadlocks on this field and had to disable this behavior which is why I came to post before I saw this. When I was experiencing deadlocks this was with a 1ms delay, and I'm not sure if increasing the delay will decrease the likelihood of a deadlock.
> 
> @sunli829 it occurs to me that there are several ways in which crossbeam could be used as to make this lock free, either via crossbeam deque or crossbeam channels. Still brainstorming on that though

`DataLoader` will not cause deadlock, if this problem really exists, please help me to reproduce it. 🙂

**Comment by servonlewis** [comment]
> > I originally addressed this issue by use of preloads, which could be as simple as using a lookahead to do batch load and having field resolvers that check for preloaded data. That pattern works well and has the fastest response times by virtue of there being no locks and no delays, but it misses the opportunity to batch load across independent requests which is preferable at scale. I thought it to be cleaner to use the dataloader and built out some new behavior using it, but then we experienced deadlocks on this field and had to disable this behavior which is why I came to post before I saw this. When I was experiencing deadlocks this was with a 1ms delay, and I'm not sure if increasing the delay will decrease the likelihood of a deadlock.
> 
> > 
> 
> > @sunli829 it occurs to me that there are several ways in which crossbeam could be used as to make this lock free, either via crossbeam deque or crossbeam channels. Still brainstorming on that though
> 
> 
> 
> `DataLoader` will not cause deadlock, if this problem really exists, please help me to reproduce it. 🙂

Hey there, I believe I am receiving a deadlock on a specific field resolver that users load one dataloader. 

Can I please receive help on this? I can upload my code when I get home tonight.

**Comment by Bajix** [comment]
> `DataLoader` will not cause deadlock, if this problem really exists, please help me to reproduce it. 🙂

When I ran into deadlocks it was because I was using `once_cell::sync::Lazy` with static instances and hadn't thought through this problem enough. I was trying to accomplish global batching, and I also had so many loader types that I didn't want to add all of these when creating the request. For anyone who's integrating this now using the DataLoader in this library, they should avoid static use and should instead construct DataLoader's for every type and use request.data to add these so that later within field resolvers you can do ctx.get_unchecked and receive the respective loader for that request. As a means to simplify constructing DataLoaders for every type per request, one could use `inventory` to submit a registry of boxed helper functions; this way you can iterate over the wrapper type and pass into each a mut request to that's responsible for attaching the DataLoader of the respective type. This is same technique I used [here](https://github.com/Bajix/channel-loader-rs/commit/04e3ee3f76bac108a97bf42eee1c49cc692a0df6), and I'm sure there's a simple solution here to be had to make it such that DataLoader's submit their construct functions via a macros. 

As far as what I was trying to accomplish insofar as doing global batching, I did so with crossbeam deque via thread local deque workers and work-stealing task handlers that steal across all threads and this turned out to be a really great and highly performant solution, which can be viewed [here](https://github.com/Bajix/channel-loader-rs).
