### ISSUE TITLE
Peovide a way to filter outgoing subscription stream

### ISSUE THREAD

**Issue by nicolaiunrein** [async-graphql/async-graphql#486]
I ran into the following problem:

## Description of the problem
I‘m serving a changefeed as a graphql subscription with non-trivial events. I have filtered the feed so that only distinct events are produced. Meaning if two subsequent events which are equal are produced only the first will ever come out of the changefeed. The second gets discarded. The problem I have now is that when serving these events through async-graphql a subscriber may only be interest in a couple of fields. While two events may be different the resolved query may produce **equal** events, resulting in unnecessary network traffic and confusion on the client side.

## Possible Solutions 
I wondered how difficult it would be to provide a way to inspect, map, filter etc. the stream after it has been resolved. If that is not feasible maybe we can implement a way to do the resolution ourselves  and serve a "raw" stream of resolved events to the SubscriptionRoot. 

## General Questions
What do you think? Is this something other people would be interested in or have solved? Would it be possible to implement? Is it worth it?

**Comment by leebenson** [comment]
@nicolaiunrein, I may be misunderstanding the question, but can't you just map/filter/transform a stream _before_ returning it in a resolver?

**Comment by leebenson** [comment]
I re-read it and think I see what you mean now. You want a way to get the stream of the _actual JSON_ returned, and then do "post processing" on it rather than filtering the original stream, which isn't aware of the fields that are being requested?

**Comment by leebenson** [comment]
#364 may be relevant. You could look at the actual fields being requested by the subscription, and drop events where the subset of fields requested matches a prior observed value.

This should be fairly simple to do by creating having an implementation of `Eq` for a custom struct which compares based on fields requested, and ignores fields that aren't part of that set.

So assuming a possible query of:

```gql
{
  a
  b
  c
}
```

Where three three event payloads are:

```json
[
  {
    "a": 1,
    "b": 1,
    "c": 1
  },
  {
    "a": 1,
    "b": 2,
    "c": 2
  },
  {
    "a": 1,
    "b": 3,
    "c": 3
  },
]
```

And the requested query is:

```gql
{
  a
}
```

Would return just:

```json
{
  "a": 1
}
```

... one-time, since the `Eq` comparison would ignore field b and c for equality.

**Comment by nicolaiunrein** [comment]
> do "post processing" on it rather than filtering the original stream, which isn't aware of the fields that are being requested?

 That’s exactly what I meant!

**Comment by nicolaiunrein** [comment]
Ah lookahead is perfect for my case! Thank you that resolved my issue! Thank you!! I wasn’t aware of it.
