### ISSUE TITLE
Discrepancies between `PageInfo` implementation and the Relay specification

### ISSUE THREAD

**Issue by msk** [async-graphql/async-graphql#520]
## Expected Behavior

[`PageInfo::start_cursor`](https://docs.rs/async-graphql/2.8.5/async_graphql/types/connection/struct.PageInfo.html#structfield.start_cursor) and [`PageInfo::end_cursor`](https://docs.rs/async-graphql/2.8.5/async_graphql/types/connection/struct.PageInfo.html#structfield.end_cursor) shouldn't be `Option`.

The [GraphQL Cursor Connections Specification](https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo.Fields) says they are non-null.

> `PageInfo` must contain fields `hasPreviousPage` and `hasNextPage`, both of which return non‐null booleans. It must also contain fields `startCursor` and `endCursor`, both of which return non‐null opaque strings.

## Actual Behavior

The type of [`PageInfo::start_cursor`](https://docs.rs/async-graphql/2.8.5/async_graphql/types/connection/struct.PageInfo.html#structfield.start_cursor) and [`PageInfo::end_cursor`](https://docs.rs/async-graphql/2.8.5/async_graphql/types/connection/struct.PageInfo.html#structfield.end_cursor) are `Option<String>`.

## Steps to Reproduce the Problem

1. Read [Sec 5.1](https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo.Fields) of the GraphQL Cursor Connections Specification.
2. Compare the description of the fields with the [implementation](https://docs.rs/async-graphql/2.8.5/async_graphql/types/connection/struct.PageInfo.html).

## Specifications

- Version: 2.8.5

**Comment by sunli829** [comment]
> ## Expected Behavior
> [`PageInfo::start_cursor`](https://docs.rs/async-graphql/2.8.5/async_graphql/types/connection/struct.PageInfo.html#structfield.start_cursor) and [`PageInfo::end_cursor`](https://docs.rs/async-graphql/2.8.5/async_graphql/types/connection/struct.PageInfo.html#structfield.end_cursor) shouldn't be `Option`.
> 
> The [GraphQL Cursor Connections Specification](https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo.Fields) says they are non-null.
> 
> > `PageInfo` must contain fields `hasPreviousPage` and `hasNextPage`, both of which return non‐null booleans. It must also contain fields `startCursor` and `endCursor`, both of which return non‐null opaque strings.
> 
> ## Actual Behavior
> The type of [`PageInfo::start_cursor`](https://docs.rs/async-graphql/2.8.5/async_graphql/types/connection/struct.PageInfo.html#structfield.start_cursor) and [`PageInfo::end_cursor`](https://docs.rs/async-graphql/2.8.5/async_graphql/types/connection/struct.PageInfo.html#structfield.end_cursor) are `Option<String>`.
> 
> ## Steps to Reproduce the Problem
> 1. Read [Sec 5.1](https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo.Fields) of the GraphQL Cursor Connections Specification.
> 2. Compare the description of the fields with the [implementation](https://docs.rs/async-graphql/2.8.5/async_graphql/types/connection/struct.PageInfo.html).
> 
> ## Specifications
> * Version: 2.8.5

If the returned result set is empty, should `startCursor` and `endCursor` return empty strings? I did not see this described in the spec, what do you think? 😁

**Comment by msk** [comment]
> If the returned result set is empty, should `startCursor` and `endCursor` return empty strings? I did not see this described in the spec, what do you think? 😁

I think empty strings are reasonable choices.

**Comment by gf3** [comment]
this is [up for debate](https://github.com/facebook/relay/pull/2655) and might change soon

**Comment by lilyball** [comment]
Note: https://github.com/facebook/relay/pull/2655 was merged (though the website hasn't been updated yet).

However, the spec is still buggy here. In particular, `PageInfo` is defined as using _opaque strings_ rather than using the previously-defined "cursor type"[^1].

Even if the spec is not updated in response to my issue, I would still strongly recommend that `async-graphql` fix its own definition of `PageInfo` to use the explicit cursor type. The usage of `String` here is especially a problem for clients in a strongly-typed language like Rust as it means I cannot just take an `endCursor` and pass that to an `after:` argument, I must instead convert it into my cursor type first (which requires my cursor type even support coercing arbitrary strings to it).

[^1]: Also the definition of _cursor type_ is confusing in that cursors are allowed to be defined as nullable or non-null, and this conflicts with the need to have cursors be non-null in edges[^2] and nullable in `PageInfo`. I've filed https://github.com/facebook/relay/issues/3826 against the spec itself.
[^2]: The definition in the spec right now allows cursors in edges to be nullable, as this is where _cursor type_ is defined, but having a null cursor on an edge would pose a difficulty in working with the pagination API (see my comment https://github.com/facebook/relay/issues/3826#issuecomment-1059592419).

I believe the proper fix here is to redefine `PageInfo` to have a `<C: CursorType>` parameter and to use `Option<C>` as its cursors. It could specify `<C: CursorType = String>` in order to preserve backwards compatibility at an API level[^3] with any clients that use the `PageInfo` type, although from skimming the API right now I don't actually see `PageInfo` used directly so I'm honestly not sure why it's even exposed. In any case, the defaulted type parameter would allow for doing this as a minor change, and `async-graphql` can internally use `PageInfo<C>` instead of just `PageInfo` and the generated GraphQL schema would have the new cursor type.

[^3]: I'm not sure what compatibility policy `async-graphql` has on changes that modify existing schemas. Doing this as a minor update to `async-graphql` could mean that a strongly-typed language like Rust that both generates and consumes a GraphQL schema in the same workspace might fail to compile after a `cargo update` due to the client side being affected by the GraphQL schema change. I imagine this is true for many other potential changes as well though.

    However, speaking as someone who is writing Rust code to consume a schema generated by `async-graphql`, the current behavior is very problematic in that I'm being forced to add a `<Cursor as From<String>>` impl just so I can convert `PageInfo`'s cursors even though I would much prefer to statically prevent my crate from synthesizing a cursor.
