### ISSUE TITLE
Best practice for cursors?

### ISSUE THREAD

**Issue by onx2** [async-graphql/async-graphql#563]
After reading through https://graphql.org/learn/pagination/ it seems using an opaque cursor is preferred (they suggest base64 encoding the offset or id). In the [example](https://async-graphql.github.io/async-graphql/en/cursor_connections.html), `usize` is used. After some modifications to the example I was able to get it working but I can't seem to get the `cursor` input on `Edge::new()` to accept a `String`. Does this library require `usize` or can I make it a `String`?

```rust
// Return type for my query
Result<Connection<String, Book>>

// query( ...
// let connection = ...omitting most of this for brevity

connection.append(
  books
  .into_iter()
  .enumerate()
  .map(|(idx, book)| {
    Edge::new(encode(idx + start), book)
  }),
);

Ok(connection)
//).await
```

**Comment by leebenson** [comment]
@onx2, you might find some inspiration here, for how we implemented a "base64" cursor comprised of a name/index: 

https://github.com/timberio/vector/blob/master/src/api/schema/relay.rs

**Comment by onx2** [comment]
Thanks for posting! This looks like exactly what I'm trying to accomplish 👏🏼 I'll definitely be able to draw inspiration from it.

I'm curious if the wrappers you've created, or a variation, make sense as part of the core library because of the relay spec recommendations for cursors?

**Comment by leebenson** [comment]
There may be some opportunities for boilerplate-reduction with some out-the-box defaults.

One thing to note is that the GraphQL spec is purposefully opaque on cursors. They can effectively be any data type that makes sense to the implementing application, which is probably why there isn't a one-size-fits-all approach.

For us at Vector, our cursors are (currently) a base64'd version of "Cursor:X", where the first part is literally the static text "Cursor" and "X" is a record offset.

Other applications may instead implement them as a form of "global" cursor, which encodes both an offset as well as the record type. IIRC, some original Relay tutorials I read used this approach, where the cursor itself was enough to uniquely identify both an underlying table _and_ a row offset.

All this to say -- our format won't make sense for every use-case.

The idea of cursors being opaque (both in specification, and readability to an end-user) is that they ought to be meaningless to a human reader. Base64 is often used as the serialisation format to encode an identifier/offset (at least where transmitting that data in plain text isn't a concern) as a means to convey that information without having to mean anything to the end-user.

But if you don't need the extra wrapping and a simple numeric value is sufficient, then `usize` would work just as well.

**Comment by onx2** [comment]
Got it - thank you for the detailed explanation and link to the Vector repo, it has been incredibly helpful!

**Comment by azzamsa** [comment]
@leebenson  Sorry to comment on the closed issue. I don't think opening a new issue here or in the Vector repo is better.

For the context, I have implemented Relay-like pagination inspired by Vector `vector/blob/master/src/api/schema/relay.rs`.  All works fine. But one thing I would like to ask is that I saw Vector fetch **all** the data the slice it according to the params.

What I want is to pass `(after, before, first, last)` down to the SQL query level (in my case).

``` rust
// https://github.com/vectordotdev/vector/blob/8119ed5f7480ef3ba8de1fdea9f49534c2ebed07/src/api/schema/components/mod.rs#L128

        relay::query(
            components.into_iter(),      // <--- ALL the data
            relay::Params::new(after, before, first, last),
            10,
        )
        .await
    }
```

Isn't this impact the performance if we have a large set of data?

Why not doing something like:

```diff
- let mut components = state::get_components();

+ let mut components = state::get_components(after, before, first, last);
```

So that the app only fetches the required data, not all the data.

---

I am looking for inspiration to do Relay-like pagination using Rust with Async-GraphQL. But after looking around, Vector `vector/blob/master/src/api/schema/relay.rs` was the *only* inspiration.

**Comment by leebenson** [comment]
Thanks for the comment, @azzamsa.

In Vector, all component state is held in memory, so there's not a great benefit to limiting data retrieval; the slice already exists in full.

In a DB scenario, absolutely, retrieval is far more costly, and cursoring should feed through to limit the scope.

**Comment by azzamsa** [comment]
> In Vector, all component state is held in memory, so there's not a great benefit to limiting data retrieval; the slice already exists in full.

Oh, I see.

I have implemented the Relay-like pagination based on 1) [Bruno Scheufler's Paginating Large, Ordered Data Sets with Cursor-Based Pagination](https://brunoscheufler.com/blog/2022-01-01-paginating-large-ordered-datasets-with-cursor-based-pagination#an-introduction-to-cursor-based-pagination) 2) [Your Pull-Request](https://github.com/vectordotdev/vector/pull/5747/commits) and 3) [Github GraphQL playground](https://docs.github.com/en/graphql/overview/explorer)

These are my steps:

- [feat: in-house relay like pagination](https://github.com/azzamsa/nahla/commit/a0b8c4e246c68164bd3155f6c6c732256e600d03)
- [feat: base64 cursor](https://github.com/azzamsa/nahla/commit/f0d779158671e9a4b152ebc9d3429eaee84ff13c)
- [feat: total count in pagination](https://github.com/azzamsa/nahla/commit/6db9e6f37547d1388ef163d9f465ed13a9d4ed21)

Since we don't have many resources regarding Relay-like pagination in Rust. I would like to ask the suggestion here. Is there any part of my code that can be improved? @leebenson @sunli829 

Hopefully, It can be an example for other newcomers.
Thanks.
