### ISSUE TITLE
Is it possible to pass additional params to dataloader?

### ISSUE THREAD

**Issue by onx2** [async-graphql/async-graphql#586]
I'd like to pass in query options to my dataloader so I can limit and offset the results using relay spec. I'm currently having postgres handle my sort, limit, and offset for my relay implementation but I'm not sure how I can make this work alongside a dataloader since the `load` fn only accepts `(&self, keys: &[K])`.

For example, if I wanted to select books from authors in this way:

```graphql
query AuthorsBooks {
  authors(first: 100) {
    // edges
    id
    name
    books(first: 10) {
      // edges
      id
      title
    }
  }
}
```

I could sort and filter outside of postgres but I imagine this would be slow to first query `<n>` authors and `<n>` books, which could be millions, then slice it up to return to the client.

```rust
pub struct SortOptions {
    pub field: String,
    pub desc: bool,
}

pub struct QueryOptions {
    pub limit: i64,
    pub offset: i64,
    pub sort: SortOptions,
}

impl Loader<Uuid> for AuthorBooksLoader {
    type Value = Vec<Book>;
    type Error = String;


    async fn load(
        &self,
        author_ids: &[Uuid],
        query_options: QueryOptions
    ) -> Result<HashMap<Uuid, Self::Value>, Self::Error> {
        let QueryOptions { limit, offset, sort } = query_options;
        let sql = SqlBuilder::select_from("books")
                    .field("*")
                    .order_by(sort.field, sort.desc)
                    // Something like this for the sql
                    .and_where("author_id = ANY($1)".bind(author_ids))
                    .limit(limit)
                    .offset(offset)
                    .sql()?;

        let books = sqlx::query_as::<_, Book>(sql.as_str())
                    .fetch_all(&self.pool)
                    .await
                    .expect("Couldn't get books".into())

        Ok(books
            .into_iter()
            .into_group_map_by(|book| book.author_id))
    }
}
```

**Comment by bram209** [comment]
The data loader is generally not used for pagination but to rather batch all requests for a resource together, so you can easily retrieve all of them in one go.

I could see two approaches:
1. You run you paginated query but only fetch the IDs, then pass these ID's through a data loader to utilize it's batching / caching capabilities
2. Do your paginated queries without data loader but populate it's cache afterwards if it seems fit

**Comment by onx2** [comment]
Thanks for your suggestions! I think the first approach would work well for me.

At a higher level though... does having nested pagination even make sense? I'm just working through as many examples as I can think of to learn more about rust and graphql so perhaps this is just a nonsensical way to build an API?

**Comment by Miaxos** [comment]
Well, it depends on your schema, and it depends on your consumers, it can add complexity for the front-end part but we already used a pattern like this for a specific use case at my old company.

I suggest avoiding datacaching first and just monitor this query and depending of the usage, add either a cache or implement a @defer directive to stream result to your client and stream result from your db.
When we had this use case, we just did it without datacaching first, with a timeout on the graphql query and some alerting on the query.

You could just expose your book query as a usual query and use in your Author entity, it allows you to only implement this once, and you just have to add memoization per query if you just want to avoid doing it multiple time:
```graphql
query AuthorsBooks {
  booksByAuthor(authorId: id, first: 10) {
    id
  }
  authors(first: 100) {
    // edges
    id
    name
    books(first: 10) {
      // edges
      id
      title
    }
  }
}
```

```rust
impl Author {
  async fn books<'ctx>(&self, ctx: &'ctx Context<'_>, after: Option<String>, before: Option<String>, first: Option<i32>, last: Option<i32>) -> FieldResult<Connection<String, Book, EmptyFields, EmptyFields>> {
    BookQuery::books_by_author(&BookQuery {}, &ctx, author_id: &self.id, after, before, first, last).await
  }
}

```

**Comment by vuong-cuong-phoenix** [comment]
Hello, sorry for commenting on a closed issue, but I've found a solution which I think is very optimal. I'm new to *Rust* and *async-graphql* but I hope the solution can help.

First, remind that the main purpose of the `DataLoader` is to batch ***information*** via the `load_one(key: K)` function, and then execute some code based on collected `keys: &[K]`.
Second, According to the [docs](https://docs.rs/async-graphql/latest/async_graphql/dataloader/trait.Loader.html), this `K` must implement `Send`, `Sync`, `Hash`, `Eq` and `Clone` traits, especially the `Hash`, `Eq` traits because in the end, we need to return a `HashMap<K, Self::Value>` and the `DataLoader` will use the key (`K`) to compare and then correctly map back the value (`Self::Value`) to the right object resolver which called `load_one(key: K)` function.

So, to send more ***information*** to the `DataLoader`, we can create a struct for our `K` and implement required traits, like the following:

```rust
#[derive(Clone)]
pub struct PaginatedId {
    id: i32,
    // `Option<T>` is not required, just my taste to reduce some redundant code
    // since I don't want to waste memory to initialize it but not use it at all (see below).
    params: Option<PaginatedParams>, 
}

impl PartialEq for PaginatedId {
    fn eq(&self, other: &Self) -> bool {
        // By default, when derive `PartialEq`, it will equally compare each field.
        // In our situation, we don't need that, we only need to compare our good-old `id`.
        self.id == other.id
    }
}

impl Eq for PaginatedId {}

impl Hash for PaginatedId {
    fn hash<H: Hasher>(&self, state: &mut H) {
        // Again, we only need to hash our `id`.
        self.id.hash(state);
    }
}

// Some utility functions.
impl PaginatedId {
    pub fn new(id: i32, params: PaginatedParams) -> PaginatedId {
        PaginatedId {
            id,
            params: Some(params),
        }
    }

    pub fn with_id(id: i32) -> PaginatedId {
        PaginatedId { 
            id, 
            params: None // Here, just pass `None` when we don't need it.
        }
    }

    pub fn id(&self) -> i32 {
        self.id
    }
}

// The `InputObject` that we receive in the resolver.
#[derive(InputObject, Clone, Copy)]
pub struct PaginatedParams {
    #[graphql(default = 4)]
    pub size: i32,
    pub page: i32,
}
```

And then, the code for our `DataLoader`:

```rust
pub struct AuthorBooksLoader {
    db_pool: Pool<Postgres>
}

impl AuthorBooksLoader {
    pub fn new(db_pool: Pool<Postgres>) -> AuthorBooksLoader {
        AuthorBooksLoader { db_pool }
    }
}

#[async_trait]
// Use the `PaginatedId` as the generic type of `Loader<K>`.
// This `DataLoader` is just an example of mine to get a list of books
// written by each author in the list of authors we queried and pass to `DataLoader`
impl Loader<PaginatedId> for AuthorBooksLoader {
    type Value = Vec<Book>;
    type Error = Arc<sqlx::Error>;

    async fn load(
        &self,
        // We should have
        keys: &[PaginatedId],
    ) -> Result<HashMap<PaginatedId, Vec<Book>>, Self::Error> {
        // Extract our `params` and execute some queries.
        // --snip--
    }
}
```

And then, in the resolver, we can easily use it like with our scalar `id`:
```rust
#[ComplexObject]
impl Author {
    pub async fn books(&self, ctx: &Context<'_>, params: PaginatedParams) -> Result<Vec<Book>> {
        let loader = ctx.data::<DataLoader<AuthorBooksLoader>>()?;

        Ok(loader
            .load_one(PaginatedId::new(self.id, params))
            .await?
            // If there is no `Book` found with our newly created `PaginatedId` above,
            // we return the default value of `Vec<T>` which is `vec![]`.
            .unwrap_or_default())
    }
```

***One bonus tip***:
Remind to my example, I'm using *PostgreSQL* to demonstrate and the `author` entity has 1-N relationship with `book`. The table DDL looks like this:
```sql
CREATE TABLE author (
    id 		SERIAL PRIMARY KEY,
    name 	        VARCHAR NOT NULL,
    created_at 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE book (
    id 		SERIAL PRIMARY KEY,
    name           VARCHAR NOT NULL,
    created_at 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    author_id 	INTEGER NOT NULL REFERENCES author(id) ON DELETE CASCADE
);
```
If not implementing pagination, I could easily write 1 simple query to get all the books like so:
```sql
SELECT id, name, created_at, author_id
FROM book
WHERE author_id = ANY($1)
ORDER BY author_id, id
```
and then map to the `HashMap<PaginatedId, Vec<Book>>` easily.
However, since this query cannot group and then paginate based on each `author_id`, we need to find a way to achieve our goal:
1. You can naively run a transaction and loop over our `keys: &[PaginatedId]` and set the `LIMIT` and `OFFSET` for each query and then `UNION` all of them. This way is fine since the N+1 problem is costly because we need to create a separate connection and the overhead of it is too much to deal with. By using this way, we just make 1 connection and then run our transaction which contains our multiple queries.
2. A better way could be using the `ROW_NUMBER()` window function and `PARTITION` like the following:
  ```sql
  SELECT *
  FROM (
      SELECT
          *,
          row_number() OVER (PARTITION BY author_id ORDER BY id) AS author_row_num
      FROM book
      WHERE author_id = ANY($1)
  ) t
  WHERE t.author_row_num <= $2 AND t.author_row_num > $3;
  ```
  *Note:* `$2` is `LIMIT + OFFSET` and `$3` is `OFFSET`
3. The above solution seems to be better than the first one, but by using `PARTITION` early, we traversed all the books in our `book`, and later we cut it off with our last `WHERE` condition. Therefore, I suggest using the `LATERAL JOIN` query below:
  ```sql
  SELECT t.*
  FROM
      author a
      JOIN LATERAL (
          SELECT b.id, b.name, b.created_at, b.author_id
          FROM book b
          WHERE b.author_id = a.id
          ORDER BY b.id
          LIMIT $1
          OFFSET $2
      ) t
      ON TRUE
  WHERE a.id = ANY($3);
  ```

**Comment by dvtkrlbs** [comment]
Hey I don't think this issue addresses my use case. In my use case I am using postgres with row level security policies and have to run my queries in a transaction since parameters necessary for the policies have to be set as session variables. How can I address this use case? Is it possible to inject a dataloader to the schema at the request handler level ?
