### ISSUE TITLE
Access the query context inside an extension

### ISSUE THREAD

**Issue by Miaxos** [async-graphql/async-graphql#589]
Hello!

When we manipulate queries / mutation / subscription in async_graphql, we have the `Context` which contains a lot of methods and data with the `QueryEnv` it would be interesting to be able to change this execution context within an extension, or at least to be able to read it ( we have response headers, variables etc... )

Right now when we execute a GraphQL query, we prepare our Context with the `prepare_request`
https://github.com/Miaxos/async-graphql/blob/886c58bb903066d60fb183becc49c53e79e617ce/src/schema.rs#L493-L520  to generate a Context with a Arc<QueryEnv> inside.

Would it make sense to you to be able to access this element within the extensions ? We could modify the create_context for the `ExentensionContext` and add an optional arg to add this Arc<QueryEnv> so we could access it within Extensions

**Comment by Erik1000** [comment]
I would love to see this and it totally makes sense. It would give way more possibilities to an ``Extension``! I've actually found this issue, because I was looking if Extensions could access the ``Context`` with ``QueryEnv`` and what to do if I want to make a PR. Unfortunately there are no comments and it's quite hard to understand the code. @sunli829 since Miaxos is on vacation and you probably best understand your code, could you implement this? I guess it would help in a lot of cases (e.g. #623, maybe #466 depending on the implementation).

I would be happy to test/implement it!

**Comment by sunli829** [comment]
Just want to access `QueryEnv` in the extension?

If you just want to access `Context::Data`, `ExtensionContent` provides the corresponding method. 🙂

**Comment by Erik1000** [comment]
I know that the QueryEnv stores the Data which can be accessed via ``Context.data::<T>()`` but that's not what I'm interested in. I'm more interested in the [``fragments``](https://docs.rs/async-graphql/2.9.14/src/async_graphql/context.rs.html#212) for example, because with this, you could build a [``Lookahead``](https://docs.rs/async-graphql/2.9.14/async_graphql/struct.Lookahead.html) object. The ``Context`` has [a method](https://docs.rs/async-graphql/2.9.14/async_graphql/context/struct.ContextBase.html#method.look_ahead) to build that from the QueryEnv, the [``ExtensionContext``](https://docs.rs/async-graphql/2.9.14/async_graphql/extensions/struct.ExtensionContext.html) does not (cuz it can't).

This is just an example where ``QueryEnv`` would be helpful. There are many other things where it would be helpful too.

**Comment by sunli829** [comment]
I will look into how to get `Context` from `ExtensionContext`, maybe this is very difficult.
