### ISSUE TITLE
Partial Entity idea

### ISSUE THREAD

**Issue by Miaxos** [async-graphql/async-graphql#616]
Hello, I'm currently trying to create a little project based on `async-graphql` and while doing so, I stubbled uppon an old issue I had: how could we create `PartialEntity` ?

## What is a Partial Entity?

Sometimes, you have an Entity, let's say you have an `Article`.
```rust
pub struct Article {
  pub id: Uuid,
  pub project_id: Uuid,
  pub title: String,
  pub subtitle: Option<String>,
  pub extra_data: Option<String>,
}
```

And you have way to get these articles, but at some point, you have a to do a call, where you have only part of the Articles data, for instance, when you do a call to get a Page, you'll be able to get some data from an Article: id, project_id, title, subtitle, but not the extra_data (they exists, but this call cannot give them to you). So in `async-graphql`, you re-do a call to get the actual Article entity with a dataloader for instance event if these extra_data where not requested, or you put a logic to check the Selection, and create another behaviour if there is no `extra_data` in the query.

What I imagine as a `PartialEntity` is an Entity which could have partial data, but the same methods as the Entity, in this example, if we do request the `project_id` from the `PartialArticle` fine, you get it, but when you request `extra_data` from this PartialArticle, it'll fetch the whole `Article` and hydrate the `PartialArticle` with the `Article` data. 

I was wondering how to do that, I do not know how I could create a behavior which would run depending of the fields requested.

I think it could benefit `async-graphql` to have these kind of struct, but it's more like an open question on how we could create a structure like that.

Right now, my idea was to create something like this (but I don't like it right now):

```rust
enum PartialState<T> {
  Partial(T),
  Nothing,
}

pub struct PartialArticle {
  pub id: Uuid,
  pub project_id: PartialState<Uuid>,
  pub title: PartialState<String>,
  pub subtitle: PartialState<Option<String>>,
  pub extra_data: PartialState<Option<String>>,
  partial: bool,
}

impl PartialArticle {
  async fn get_article(&self) -> () {
    if self.partial == false {
      fetch_article_and_hydrate_self().await; // With interior mutability of the struct mb, idk yet 
      self.partial = true;
    }
  }
  
  pub async fn project_id(&self) -> anyhow::Result<Uuid> {
    // If partial state -> unwrap or get_article & unwrap.
    ...
  }
  
  pub async fn entity(&self) -> Article {
    // get_article -> transform to Article
  }
}

```

## Three questions

What do you think about it?
Do you have an idea/suggestion for it or a better way to do what I want?
Would it be a nice struct to use in `async-graphql`?

Thx for reading!

**Comment by sunli829** [comment]
Sorry for the late reply.
I have encountered similar problems, so I fully understand what you want to do. 
I used `LookAHead` to solve this problem, but I had to make an object's members all `Option`, which does not seem elegant enough.
`PartialState` looks great, and I look forward to your further attempts.🙂

**Comment by Erik1000** [comment]
I'm stuck on exactly the same problem right know. Setting all fields ``Option<T>`` was my thought too, but as you said, that's pretty ugly.

**Comment by Erik1000** [comment]
I've been thinking, could we provide the LookAHead to Dataloaders @sunli829 ? This would open way more possibilities.

**Comment by sunli829** [comment]
Maybe we can design some API to do this better, but I still don't have a good idea how to do it.

**Comment by Erik1000** [comment]
Well if we could pass the requested fields to the dataloader, the dataloader could get only the fields that are needed and could implement caching on a field basis. That was my idea. A implementation could then check which fields are needed, look up the cache and if needed, fetch them.

**Comment by Erik1000** [comment]
I think I have a good approach which we can work out to be a solution. I'll explain and maybe create a PR tomorrow. It would require the Context in the loader function or at least the requested fields.

The basic idea is to have the fields selected in the database query based on the required fields. With postgres, this works just fine:
```sql
SELECT
            CASE WHEN $1 = true THEN email ELSE NULL END email,
            CASE WHEN $2 = true THEN first_name ELSE NULL END first_name,
            CASE WHEN $3 = true THEN last_name ELSE NULL END last_name
 FROM users
 WHERE user_id IN ($4)
```
with sqlx, you can then set $1-3 to true if the field is requested or to false if not. You could also check if each field is in the cache and only query for it if needed. 
If you understand what I mean, you're welcome to tell me your opinion. Of course, a struct too keep track of the fields available e.g. Option<T> or @Miaxos  idea is still needed. But at least you can implement a sexy dataloader with this. I'll provide actual code tomorrow. good night

**Comment by Miaxos** [comment]
Well, you should try to create a PR with your idea, it might be a little different of what I think of, I think I see what you want to do, and it would solved a lot of issues, some of them linked to what I want to do.

In my idea, this structure shouldn't be really tied to any async-graphql stuff and so it wouldn't be tied to a dataloader too, it's a structure which store data, and only some of it is available, and when we request some which aren't, a function to hydrate it and to transform it into the sub-structure behind it is executed.

What I would love is that if we have a function:

```rust
fn something(data: DataType) -> () {
  let a = data.a_field();
}
```
We could create an associated PartialType for DataType to have a `PartialDataType` which could be used with this function `something` and when this `PartialDataType` doesn't the A field, it would execute the function to hydrate `PartialDataType` and pseudo-cast it into a `DataType`.

I have the idea, but I didn't have any time to try implementations of this idea and I am going to vacations for two weeks, I will work on it when I return.

**Comment by Erik1000** [comment]
The main difference we have is that your idea is field based e.g.
```rust
pub struct Article {
  pub id: Uuid,
  pub project_id: Uuid,
  pub title: String,
  pub subtitle: PartialDataType<String>, // thats only a single field
  pub extra_data: PartialDataType<String>, // that too
}
```
This would probably needs two functions (a function for each field) to fetch the data which could be only resolved with two DataLoaders afaik. Except if there's a DataLoader for Article which keeps track of all fields requested. E.g. if a GraphQL query had subtitle and extra_data, it would request both fields in one query for all articles, selected.
So imagine a query where a user wants to list all articles they _can_ read (e.g. they have a subscription):
Schema:
```graphql
Article {
    id: ID!,
    project_id: ID!,
    title: String!,
    subtitle: String!,
    extra_data: String!
    wrtier: User!,
}

"
An object to recieve information about the current user.
"
User {
    available_articles: [Article!]!
    id: ID!,
    first_name: String!,
    last_name: String!,
    email: String!,
}


type Query {
    self: User
}
```

The query would look something like this:
```graphql
self {
    available_articles {
        id
        title
        subtitle
        extra_data
    }
}
```
In a naive approach, extra_data and subtitle each had a ``PartialData`` struct with a function (your ``something(data: Data)`` function) so the resulting SQL would look something like (if you use DataLoaders like you can right know)
```sql
SELECT extra_data FROM articles WHERE id IN ($1)
SELECT subtitle FROM articles WHERE id IN ($2)
```
For all articles, that's two SQL queries where it could be only one. I mean, with only two fields, it's not that bad, but if you decide only to fetch data then they are needed, like I do, this would suck.

Imagine a PartialData object that would use a DataLoader which keeps track of all fields that are requested and at the end, combines all required instances of a object along with it's PartialData fields. In the example above, the sql would only be one query no matter how many fields or articles there are (with DataLoader, including fetching the other fields of ``Article``):
```sql
SELECT title, subtitle, extra_data FROM articles WHERE id in ($1)
```
In the user resolver for ``available_articles``, you would get a user and then call ``loader.load_one(id)`` which returns a list of all ``Articles`` for the user.

# A word about the query I sent yesterday
If you do this, the sql query needs to be flexible. You could achieve this by using something like the ``format!`` macro but that's a bad idea because it could lead to sql injections and if you use [``sqlx``](https://github.com/launchbadge/sqlx), you would also lose the compile time checks.
So yesterday we figured out a way to select fields only then they are needed without changing the sql query. The result is something like I sent:
```sql
SELECT
            CASE WHEN $1 = true THEN email ELSE NULL END email,
            CASE WHEN $2 = true THEN first_name ELSE NULL END first_name,
            CASE WHEN $3 = true THEN last_name ELSE NULL END last_name
 FROM users
 WHERE user_id IN ($4)
```
This is great, because at run time, you only provide a ``bool`` for each field to specify if you want it or not. Postgres at least will do exactly the same as if you generated a query at run time. We tested indexes which will only be used if specific fields are select and that works too.

**Comment by tmcgroul** [comment]
@sunli829 
> I have encountered similar problems, so I fully understand what you want to do. I used `LookAHead` to solve this problem, but I had to make an object's members all `Option`, which does not seem elegant enough.

If i do this way i get no exclamation point at the end of a field in a schema. Is there a solution to mark optional-field as a  non nullable?

**Comment by bbigras** [comment]
> If i do this way i get no exclamation point at the end of a field in a schema. Is there a solution to mark optional-field as a non nullable?

Is it the same as this use case that I can't figure out how to do?

```sql
CREATE TABLE public.users (
    id integer NOT NULL,
    name text NOT NULL,
    pet_name text
);
```

```graphql
query GetUsers {
  users {
    id
    name
  }
}

query GetUsersWithPets {
  users {
    id
    name
    pet_name
  }
}
```

when I query `GetUsers` I want a reply with this type:
```rs
    pub struct GetUsersUsers {
        pub id: Int,
        pub name: String,
    }
```

and when I query `GetUsersWithPets` I want a reply with this type:
```rs
    pub struct GetUsersWithPetsUsers {
        pub id: Int,
        pub name: String,
        pub pet_name: Option<String>,
    }
```

**Comment by tmcgroul** [comment]
@bbigras i am not sure that i understood you correctly...
a solution for my case is to define resolves by my own
```
struct Struct {
  field1: Option<String>,
  field2: Option<String>,
}
[#Object]
impl Struct {
  async fn field(&self, _ctx: Context) -> String {
    // i am sure that field1 is not None
    self.field.unwrap()
  }
}
```
What the case are you trying to figure out?
