### ISSUE TITLE
Serialize an enum without quotes

### ISSUE THREAD

**Issue by SadiinsoSnowfall** [async-graphql/async-graphql#790]
I want to send a GQL query to another program. In order to do so, I need to serialize the request, I didn't find a lot of info about this in the book but found the `async_graphql::to_value` function which seems to do just that.

I only have one problem, if we consider the following code :
```rust
#[derive(Serialize, SimpleObject)] 
pub struct Struct {
    pub val: EnumValue,
}

#[derive(Serialize, Enum, Clone, Copy, PartialEq, Eq)]
pub enum EnumValue {
    A, B, C
}

let value = async_graphql::to_value(Struct { val: EnumValue::B }).unwrap().to_string();
```
`value` will contains `{val: "B"}` which doesn't seems to be valid GQL (either that or the program I'm trying to communicate with doesn't accept valid GQL). When I try to send this to the other program, it refuses it because the value of the enum (here `"B"`) is passed with quotes when it expects it without quotes.

Is there a way to tell async_graphql to serialize the enum value without the quotes ?

**Comment by sunli829** [comment]
`Async-graphql` does not provide this, `to_value` is only used to generate the response.

**Comment by SadiinsoSnowfall** [comment]
Ok that's what I thought, I just wanted to make sure.
I such a feature (serializing gql input/queries) planned for this library ?

**Comment by EtienneProthon** [comment]
I think i have the same kind of issue. I use async graphql to manage schema generation and object coherence, but i use appsync from aws to manage the request so i need to parse the json input to my structs (i can't call schema execute) and there is some issues with the enums like this:
```
#[derive(Debug, Serialize, Deserialize, Enum, Eq, PartialEq, Copy, Clone)]
pub enum EPatientComorbidityFieldId {
    Hello,
    HiHowAreYou,
    NVM,
    W84ME
}
```
In the graphql schema it's generated like this:
```
HELLO
HI_HOW_ARE_YOU
NVM
W84ME
```
So the front-end is sending this strings.
If i try to parse without any `#[serde(rename_all = "SCREAMING_SNAKE_CASE")]` it fail because try to match `HELLO` to `Hello`. If i put the `SCREAMING_SNAKE_CASE` it fail because try to match `NVM` to `N_V_M` and if i put `UPPERCASE` if fail on `HI_HOW_ARE_YOU` to `HIHOWAREYOU`

How can i have the same serialization and deserialization than async graphql from a json object ? 
My current workaround is by doing this: 
```
#[serde(rename_all = "UPPERCASE")]
#[graphql(rename_items = "UPPERCASE")]
```
