### ISSUE TITLE
How are folks implementing caching?

### ISSUE THREAD

**Issue by wileymc** [async-graphql/async-graphql#849]
I'm curious what approaches people are taking to caching data from common queries.  Our API has mostly static data so I would like to implement a cache for the main queries being consumed by our front end—no need to hit the database on every request. Has anyone integrated something like redis into their dataloaders?

**Comment by jrouaix** [comment]
Hello, 

that is a good question,

Does someone have an example on how to plug a cache and make good use of the `cache_control` computed value ?

**Comment by jrouaix** [comment]
Ho wait ?! 

is it only to enable caching by client side & proxies thought `Cache-Control` header ?

If so, since all graphql queries are on the same route, how to specify a kind of `key` (a hash of the request body for example), for the man in the middle proxy to hold distinct caches from the same `/graphql` endpoint ?

Perhaps it's common knowledge, I really feel like dumb here ...
