### ISSUE TITLE
Schema first

### ISSUE THREAD

**Issue by sunli829** [async-graphql/async-graphql#91]
Some developers like `Schema first`, so I decided to support this feature.

- [x] Schema parser
- [ ] Code generator
  - [ ] async-graphql-sdl (SDL code generation core library)
  - [ ] async-graphql-gen (A command line-based code generator)
  - [ ] async-graphql-dsl-codegen (A procedural macro based code generator)
- [ ] Custom directive

**Comment by ruseinov** [comment]
Nice to have! Although in my experience it seems like the best way to proceed with graphql, however you define the schema, is producing schema from an actual implementation. But being able to generate basic structs never hurts!

**Comment by sunli829** [comment]
This code generator can get the entire schema information, so it will be more powerful than procedural macros.

**Comment by orefalo** [comment]
Neat ;-) can wait to replace my JS implementations

**Comment by sunli829** [comment]
I completed part of it, but I think it is not easy to use, and a lot of configuration parameters need to be added. So I'm wondering whether to continue? 😂

**Comment by ruseinov** [comment]
I'd say that the ability to generate basic scaffolding for Input Objects, Mutations/Queries/Subscriptions and map known scalars like Upload is a really good start as it's gonna save some typing for sure, even if it needs some manual intervention later for the gql models to map properly to the database, for example. 

Code-generated solutions always had their limitations, but it could be a good place for a developer to start lining up their object structure. It's a good tool to have in order to speed up the development and relieve programmers from typing duty, as right now one has to manually type in every query/mutation et cetera. 

The cool thing about async-graphql framework is that it's actual implementation is not code-generated, but built using macros instead, which is much better than a go-lang alternative here: https://github.com/99designs/gqlgen , because of the language limitations and the decisions made when implementing that framework. Feel free to take a look if you haven't seen it - generating scaffolding based on even a very simple schema quickly reveals it's pitfalls, maybe that'd inspire you.

**Comment by sunli829** [comment]
I've used `gqlgen`, but I don't think it works well. It requires too much configuration.

**Comment by sarendsen** [comment]
I find https://lighthouse-php.com/ has a great implementation of schema first. 
Directives can be really powerful used correctly.

**Comment by ruseinov** [comment]
> I've used `gqlgen`, but I don't think it works well. It requires too much configuration.

Not only that, but also when you need to pass some things around like database and guards/validators/auth - it becomes intolerable as there's too much plumbing involved. I don't really like it for that reason and the fact that it generates thousands of lines of code.

**Comment by Farkal** [comment]
Any news about this one ? I can try to help if you need ;)
It's the only think that prevent me to move from juniper to this lib (i use https://github.com/davidpdrsn/juniper-from-schema ) it's easier to design app directly from graphql scheme.
But it also introduce some issues because you can't derive an already declared struct so you have to create an new interface, impl From... 
I don't know if we could find a way to allow custom derivation in your implementation.

**Comment by sunli829** [comment]
Now there is a separate project to do this, thanks to @atsuhiro.

https://github.com/atsuhiro/codegen-for-async-graphql

**Comment by orefalo** [comment]
Nice, thanks for pointing it out

**Comment by mattoni** [comment]
It seems that library hasn't been updated in over two years - is there still any support for doing a schema first approach with async-graphql?

**Comment by edude03** [comment]
Wondering why as well

**Comment by orefalo** [comment]
hum... was one of the best at the time.

**Comment by coopbri** [comment]
I know it' been a couple years since this thread had some activity, but has anyone here discovered an alternative? I noticed even Juniper recommends an abandoned GraphQL -> Juniper codegen library (First paragraph in https://graphql-rust.github.io/juniper/master/schema/schemas_and_mutations.html).
